sudo: required
services:
  - docker
before_install:
  - docker build -t username/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run username/react-test npm test -- --coverage

after_success:
  - docker build -t username/frontend-prod ./frontend
  - docker build -t username/backend-prod ./backend
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to docker hub
  - docker push username/frontend-prod
  - docker push username/backend-prod