version: '3'

services:
  backend:
    build:
      context: ./backend
    # command: gunicorn core.wsgi --bind 0.0.0.0:8000
    environment:
      - IN_DOCKER=True
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on: 
      - db
  frontend:
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - '3050:80'
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
volumes:
  postgres_data: