version: '3'

services:
  backend:
    build:
      context: ./backend
    # command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/django
      - static_volumes:/django/staticfiles
      - media_volumes:/django/media
    environment:
      - IN_DOCKER=True
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:8080
    volumes:
      - react_build:/var/www/react
      - static_volumes:/var/www/django/staticfiles
      - media_volumes:/var/www/django/media
    depends_on:
      - backend
      - frontend
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  react_build:
  static_volumes:
  media_volumes:
  postgres_data: