# Generated by Django 3.2.6 on 2021-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='list_item_images'),
        ),
    ]
