# Generated by Django 3.2.6 on 2021-08-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_list', '0002_listitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
